import type { Metadata } from "next";
import "./globals.css";
import { Sidebar } from "@/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex"
      >
        <Sidebar />
        <div className="flex-1 p-4 pt-5 bg-slate-800 text-slate-200">{children}</div>
      </body>
    </html>
  );
}
